# Generated by Django 4.2.2 on 2024-05-15 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('tournament_name', models.CharField(max_length=250)),
                ('participant_id', models.IntegerField()),
                ('original_name', models.CharField(max_length=200)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('membership_requests', models.ManyToManyField(blank=True, related_name='requested_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
