# Generated by Django 4.2.2 on 2024-05-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournament_name',
        ),
        migrations.AddField(
            model_name='team',
            name='tournament_id',
            field=models.IntegerField(null=True),
        ),
    ]
