# Generated by Django 4.2.2 on 2024-05-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_team_tournament_name_team_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tournament_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
