# Generated by Django 4.2.2 on 2024-05-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_team_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_members',
            field=models.IntegerField(default=3),
        ),
    ]
