# Generated by Django 4.2.2 on 2024-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='shown',
            field=models.BooleanField(default=False),
        ),
    ]
